/**
 * Presentation-boundary translation for DB-seeded movement content.
 *
 * Audit 2026-09-15 (`/atleta/movimientos/[id]`): the Thruster detail printed
 * equipment "Barbell / Plates" and muscles "Quads, Glutes, Shoulders, Core,
 * Triceps" inside otherwise Spanish copy. That text is seeded into
 * `Movement.equipment` / `Movement.musclesWorked` (see `prisma/seed.ts`), not
 * hardcoded in `src/lib`, so the honest fix is two layers:
 *
 *  1. this mapper, so the athlete never reads English again, even on boxes
 *     whose rows were seeded months ago or generated by the AI content path;
 *  2. a seed/backfill translation, which is outside this change and is
 *     reported to the caller.
 *
 * Matching is accent- and case-insensitive and already-Spanish values pass
 * through untouched, so running this over translated rows is a no-op.
 */

function normalize(value: string): string {
  return value.trim().toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "");
}

const EQUIPMENT_ES: Record<string, string> = {
  barbell: "Barra",
  bar: "Barra",
  "pull-up bar": "Barra de dominadas",
  "pull up bar": "Barra de dominadas",
  plates: "Discos",
  plate: "Disco",
  dumbbell: "Mancuerna",
  dumbbells: "Mancuernas",
  kettlebell: "Kettlebell",
  kettlebells: "Kettlebells",
  rings: "Anillas",
  ring: "Anilla",
  "jump rope": "Cuerda de saltar",
  rope: "Cuerda",
  "climbing rope": "Cuerda de escalada",
  box: "Cajón",
  "plyo box": "Cajón",
  bench: "Banca",
  rower: "Remadora",
  "rowing machine": "Remadora",
  bike: "Bicicleta",
  "assault bike": "Bicicleta de aire",
  "echo bike": "Bicicleta de aire",
  "ski erg": "Ski erg",
  "wall ball": "Balón de wall ball",
  "medicine ball": "Balón medicinal",
  "med ball": "Balón medicinal",
  "ab mat": "Colchoneta abdominal",
  abmat: "Colchoneta abdominal",
  mat: "Colchoneta",
  rack: "Rack",
  "squat rack": "Rack de sentadilla",
  "gymnastic rings": "Anillas de gimnasia",
  bands: "Ligas",
  band: "Liga",
  "resistance band": "Liga de resistencia",
  sled: "Trineo",
  sandbag: "Costal",
  none: "Sin equipo",
  bodyweight: "Peso corporal",
  "no equipment": "Sin equipo",
  gi: "Gi",
  parallettes: "Paralelas",
  "parallel bars": "Barras paralelas",
  "dip bars": "Barras de fondos",
  "weight vest": "Chaleco con peso",
  vest: "Chaleco con peso",
  wall: "Pared",
  "wall target": "Blanco en la pared",
  harness: "Arnés",
  // Loanwords a Mexican box speaks as-is. Mapped to themselves so they are
  // explicitly "already Spanish", not an unmapped value that happens to pass.
  ghd: "GHD",
};

const MUSCLE_ES: Record<string, string> = {
  quads: "Cuádriceps",
  quadriceps: "Cuádriceps",
  hamstrings: "Isquiotibiales",
  glutes: "Glúteos",
  calves: "Pantorrillas",
  core: "Core",
  abs: "Abdomen",
  abdominals: "Abdomen",
  obliques: "Oblicuos",
  shoulders: "Hombros",
  delts: "Hombros",
  deltoids: "Hombros",
  "rear delts": "Deltoides posteriores",
  traps: "Trapecios",
  lats: "Dorsales",
  back: "Espalda",
  "upper back": "Espalda alta",
  "lower back": "Espalda baja",
  chest: "Pecho",
  pecs: "Pecho",
  triceps: "Tríceps",
  biceps: "Bíceps",
  forearms: "Antebrazos",
  "wrist flexors": "Flexores de muñeca",
  grip: "Agarre",
  "hip flexors": "Flexores de cadera",
  hips: "Cadera",
  adductors: "Aductores",
  "full body": "Cuerpo completo",
  "posterior chain": "Cadena posterior",
  cardiovascular: "Cardiovascular",
  cardio: "Cardiovascular",
};

function translate(dict: Record<string, string>, raw: string): string {
  const key = normalize(raw);
  return dict[key] ?? raw;
}

/** "Barbell" → "Barra"; "Barra" → "Barra". */
export function equipmentLabel(raw: string): string {
  return translate(EQUIPMENT_ES, raw);
}

/** "Quads" → "Cuádriceps"; "Cuádriceps" → "Cuádriceps". */
export function muscleLabel(raw: string): string {
  return translate(MUSCLE_ES, raw);
}

export function equipmentLabels(raw: readonly string[]): string[] {
  return raw.map(equipmentLabel);
}

export function muscleLabels(raw: readonly string[]): string[] {
  return raw.map(muscleLabel);
}

/**
 * Seeded descriptions leak model scaffolding ("Score: weight (kg). Tips RX:")
 * and half-English sentences. We cannot rewrite prose at runtime, but we can
 * strip the scaffolding that is unambiguously not athlete copy and translate
 * the fixed field labels the generator emits.
 */
export function cleanMovementDescription(raw: string | null): string | null {
  if (!raw) return null;
  const cleaned = raw
    // "Score: weight (kg)." — a data contract, not coaching copy.
    .replace(/\bScore:\s*[^.\n]*\.?/gi, "")
    .replace(/\bTips?\s+RX:\s*/gi, "Claves RX: ")
    .replace(/\bSetup:\s*/gi, "Montaje: ")
    .replace(/\bCues?:\s*/gi, "Clave: ")
    .replace(/[ \t]{2,}/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
  return cleaned.length > 0 ? cleaned : null;
}
